[#4083] fix missing <thread> include
Fixes the following when building against libstdc++ 11:

irods/lib/core/include/experimental_plugin_framework.hpp: In function ‘void irods::experimental::api::{anonymous}::sleep()’:
irods/lib/core/include/experimental_plugin_framework.hpp:66:31: error: ‘sleep_for’ is not a member of ‘std::this_thread’
   66 |             std::this_thread::sleep_for(std::chrono::milliseconds(500));
      |                               ^~~~~~~~~